version = 1

[[analyzers]]
name = "docker"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "vue",
    "ember",
    "meteor"
  ]
  environment = [
    "nodejs",
    "jquery"
  ]

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"